public extension UInt8 {
    // Control characters 0-31
    static let nul             : UInt8 = 0   // NUL  (Null)
    static let soh             : UInt8 = 1   // SOH  (Start of Heading)
    static let stx             : UInt8 = 2   // STX  (Start of Text)
    static let etx             : UInt8 = 3   // ETX  (End of Text)
    static let eot             : UInt8 = 4   // EOT  (End of Transmission)
    static let enq             : UInt8 = 5   // ENQ  (Enquiry)
    static let ack             : UInt8 = 6   // ACK  (Acknowledge)
    static let bel             : UInt8 = 7   // BEL  (Bell, Alert)
    static let bs              : UInt8 = 8   // BS   (Backspace)
    static let ht              : UInt8 = 9   // HT   (Horizontal Tab)
    static let lf              : UInt8 = 10  // LF   (Line Feed)
    static let vt              : UInt8 = 11  // VT   (Vertical Tab)
    static let ff              : UInt8 = 12  // FF   (Form Feed)
    static let cr              : UInt8 = 13  // CR   (Carriage Return)
    static let so              : UInt8 = 14  // SO   (Shift Out)
    static let si              : UInt8 = 15  // SI   (Shift In)
    static let dle             : UInt8 = 16  // DLE  (Data Link Escape)
    static let dc1             : UInt8 = 17  // DC1  (Device Control 1 / XON)
    static let dc2             : UInt8 = 18  // DC2  (Device Control 2)
    static let dc3             : UInt8 = 19  // DC3  (Device Control 3 / XOFF)
    static let dc4             : UInt8 = 20  // DC4  (Device Control 4)
    static let nak             : UInt8 = 21  // NAK  (Negative Acknowledge)
    static let syn             : UInt8 = 22  // SYN  (Synchronous Idle)
    static let etb             : UInt8 = 23  // ETB  (End of Transmission Block)
    static let can             : UInt8 = 24  // CAN  (Cancel)
    static let em              : UInt8 = 25  // EM   (End of Medium)
    static let sub             : UInt8 = 26  // SUB  (Substitute)
    static let esc             : UInt8 = 27  // ESC  (Escape)
    static let fs              : UInt8 = 28  // FS   (File Separator)
    static let gs              : UInt8 = 29  // GS   (Group Separator)
    static let rs              : UInt8 = 30  // RS   (Record Separator)
    static let us              : UInt8 = 31  // US   (Unit Separator)

    // Printable characters 32-126
    static let space           : UInt8 = 32  // Space
    static let exclamation     : UInt8 = 33  // !
    static let quote           : UInt8 = 34  // "
    static let numberSign      : UInt8 = 35  // #
    static let dollar          : UInt8 = 36  // $
    static let percent         : UInt8 = 37  // %
    static let ampersand       : UInt8 = 38  // &
    static let apostrophe      : UInt8 = 39  // '
    static let openParen       : UInt8 = 40  // (
    static let closeParen      : UInt8 = 41  // )
    static let asterisk        : UInt8 = 42  // *
    static let plus            : UInt8 = 43  // +
    static let comma           : UInt8 = 44  // ,
    static let hyphenMinus     : UInt8 = 45  // -
    static let period          : UInt8 = 46  // .
    static let slash           : UInt8 = 47  // /
    static let zero            : UInt8 = 48  // 0
    static let one             : UInt8 = 49  // 1
    static let two             : UInt8 = 50  // 2
    static let three           : UInt8 = 51  // 3
    static let four            : UInt8 = 52  // 4
    static let five            : UInt8 = 53  // 5
    static let six             : UInt8 = 54  // 6
    static let seven           : UInt8 = 55  // 7
    static let eight           : UInt8 = 56  // 8
    static let nine            : UInt8 = 57  // 9
    static let colon           : UInt8 = 58  // :
    static let semicolon       : UInt8 = 59  // ;
    static let lessThan        : UInt8 = 60  // <
    static let equals          : UInt8 = 61  // =
    static let greaterThan     : UInt8 = 62  // >
    static let question        : UInt8 = 63  // ?
    static let atSign          : UInt8 = 64  // @

    static let A               : UInt8 = 65  // A
    static let B               : UInt8 = 66  // B
    static let C               : UInt8 = 67  // C
    static let D               : UInt8 = 68  // D
    static let E               : UInt8 = 69  // E
    static let F               : UInt8 = 70  // F
    static let G               : UInt8 = 71  // G
    static let H               : UInt8 = 72  // H
    static let I               : UInt8 = 73  // I
    static let J               : UInt8 = 74  // J
    static let K               : UInt8 = 75  // K
    static let L               : UInt8 = 76  // L
    static let M               : UInt8 = 77  // M
    static let N               : UInt8 = 78  // N
    static let O               : UInt8 = 79  // O
    static let P               : UInt8 = 80  // P
    static let Q               : UInt8 = 81  // Q
    static let R               : UInt8 = 82  // R
    static let S               : UInt8 = 83  // S
    static let T               : UInt8 = 84  // T
    static let U               : UInt8 = 85  // U
    static let V               : UInt8 = 86  // V
    static let W               : UInt8 = 87  // W
    static let X               : UInt8 = 88  // X
    static let Y               : UInt8 = 89  // Y
    static let Z               : UInt8 = 90  // Z

    static let openBracket     : UInt8 = 91  // [
    static let backslash       : UInt8 = 92  // \
    static let closeBracket    : UInt8 = 93  // ]
    static let caret           : UInt8 = 94  // ^
    static let underscore      : UInt8 = 95  // _
    static let backtick        : UInt8 = 96  // `

    static let a               : UInt8 = 97  // a
    static let b               : UInt8 = 98  // b
    static let c               : UInt8 = 99  // c
    static let d               : UInt8 = 100 // d
    static let e               : UInt8 = 101 // e
    static let f               : UInt8 = 102 // f
    static let g               : UInt8 = 103 // g
    static let h               : UInt8 = 104 // h
    static let i               : UInt8 = 105 // i
    static let j               : UInt8 = 106 // j
    static let k               : UInt8 = 107 // k
    static let l               : UInt8 = 108 // l
    static let m               : UInt8 = 109 // m
    static let n               : UInt8 = 110 // n
    static let o               : UInt8 = 111 // o
    static let p               : UInt8 = 112 // p
    static let q               : UInt8 = 113 // q
    static let r               : UInt8 = 114 // r
    static let s               : UInt8 = 115 // s
    static let t               : UInt8 = 116 // t
    static let u               : UInt8 = 117 // u
    static let v               : UInt8 = 118 // v
    static let w               : UInt8 = 119 // w
    static let x               : UInt8 = 120 // x
    static let y               : UInt8 = 121 // y
    static let z               : UInt8 = 122 // z

    static let openBrace       : UInt8 = 123 // {
    static let verticalBar     : UInt8 = 124 // |
    static let closeBrace      : UInt8 = 125 // }
    static let tilde           : UInt8 = 126 // ~
    static let delete          : UInt8 = 127 // DEL (Delete)
}
